config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  get 'privacy_policy', to: 'contents#privacy_policy'
  get 'enter', to: 'users#enter'
  get 'about', to: 'users#about'
  get 'signup/oauth', to: 'signups#oauth'
  get 'signup/facebook', to: 'signups#oauth_facebook'
  root 'users#index'
  resources :users, only: :show
  resources :genres
  resources :user_checks
  resources :likes, only: %i[create destroy]
  resources :contents do
    resources :comments
  end
end

app/models/achievement.rb
class Achievement < ApplicationRecord
  belongs_to :user
  belongs_to :content
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check.rb
class Check < ApplicationRecord
  belongs_to :user_check
  belongs_to :content
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :content
  belongs_to :user
  validates :text, presence: true
  has_many :likes
  has_many :like_users, through: :likes, source: :user
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :genre, optional: true
  has_many :comments
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :contents
  has_many :user_checks
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
end

app/models/trophy.rb
class Trophy < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :user_checks
  has_many :checks, through: :user_checks
  has_many :likes
  has_many :comments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, omniauth_providers: %i[facebook google_oauth2]
  with_options presence: true do
    validates :email, :username, :start_date
  end
  validates :email, presence: true, uniqueness: true

  def self.from_omniauth(auth)
    @credential = SnsCredential.where(provider: auth.provider, uid: auth.uid, email: auth.info.email).first_or_create
    @user = User.where(email: auth.info.email).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.password_confirmation = Devise.friendly_token[0, 20]
    end
    @user
  end

  def trophies
    @trophys = []
    comments_length = comments.length
    likes_length = likes.length
    comment_trophies(comments_length)
    like_trophies(likes_length)
    @trophys
  end

  def comment_trophies(comments_length)
    @trophys << Trophy.find(8) if comments_length >= 1
    @trophys << Trophy.find(9) if comments_length >= 10
    @trophys << Trophy.find(10) if comments_length >= 50
    @trophys << Trophy.find(11) if comments_length >= 100
  end

  def like_trophies(likes_length)
    @trophys << Trophy.find(12) if likes_length >= 10
    @trophys << Trophy.find(13) if likes_length >= 50
  end

  def remember_me
    true
  end
end

app/models/user_check.rb
class UserCheck < ApplicationRecord
  has_many :checks
  accepts_nested_attributes_for :checks
  belongs_to :user
  belongs_to :genre
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @contents = Content.all
  end

  def show
    @content = Content.find(params[:id])
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.new(comment_params)
    @comment.save
    redirect_to content_url(id: @comment.content_id)
  end

  def edit
    @comment = Comment.find(params[:id])
    @content = @comment.content
  end

  def update
    @comment = Comment.find(params[:id]).update(comment_params)
    redirect_to content_url(params[:content_id])
  end

  def destroy
    @comment = Comment.find(params[:id]).destroy
    redirect_to content_url(params[:content_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :content_id)
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
    @comments = Comment.all
  end

  def show
    @genre = Genre.find(params[:id])
    @num = @genre.contents.first.id
    return true if @user_check = UserCheck.find_by(user_id: current_user.id, genre_id: params[:id])

    @user_check = UserCheck.new
    Genre.find(params[:id]).contents.length.times { @user_check.checks.build }
  end

  def new
    @user_check = UserCheck.new
    @user_checks = Content.last.id.times do
      @user_check.checks.build
    end
  end

  def edit
    @user_check = UserCheck.find_by(user_id: current_user.id)
    @checks = @user_check.checks.firstend
  end

  def create
    @user_check = current_user.user_checks.create(user_check_params)
    redirect_to root_path
  end

  def update
    @user_check = current_user.user_checks.update(user_check_params)
    redirect_to root_path
  end

  def user_check_params
    params.require(:user_check).permit(
      :genre_id,
      :user_id,
      checks_attributes: %i[id level flag content_id]
    )
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @comment = Comment.find(params[:li][:comment_id])
    @comment.likes.create(user_id: current_user.id)
    redirect_to content_url(id: @comment.content_id)
  end

  def destroy
    @like = Like.find(params[:id]).destroy
    redirect_to content_url(id: @like.comment.content_id)
  end

  private

  def likes_params
    params.require(:likes).permit(:user_id, :comment_id)
  end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  def sms_confirmation_send
    @profile = Profile.new
    flash.delete(:notice)
  end

  def sms_confirmation_certify
    @profile = current_user.profile.assign_attributes(profile_params)
    if current_user.profile.valid?(:sms_confirmation_send)
      current_user.profile.update(profile_params)
    else
      @profile = Profile.new
      @errors = '未記入箇所があります'
      render 'sms_confirmation_send'
    end
  end

  def oauth
    @user = User.new
    @user.email = session['devise.google_data']['info']['unverified_email'] if session['devise.google_data']
    @user.email = session['devise.facebook_data']['info']['email'] if session['devise.facebook_data']
  end

  def oauth_facebook
    @user = User.new
    @user.email = session["devise.facebook_data"]['info']['email']
  end

  def index; end

  def new; end

  def show; end

  def succesful; end

  private

  def profile_params
    params.require(:profile).permit(:phone_number, :family_name, :last_name, :kana_family_name, :kana_last_name, :postalcode, :address_prefecture, :address_city, :address_street_number, :address_building_name)
  end

  def use_check_address_nil?
    false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def enter
    render layout: nil
  end

  def about; end

  def index; end

  def show
    @user = User.find(params[:id])
    @trophys = @user.trophies
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find(session[:user_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/user_checks_helper.rb
module UserChecksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.haml
.form
  = form_for [@content, @comment] do |f|
    .input-box
      .input-box__text
        = f.hidden_field :content_id,value:params[:id]
        = f.text_area :text, placeholder: 'type a message', id: "textarea"
      .input-box__submit-btn
        = f.submit id: "edit_button"
%br/
%br/

app/views/genres/_form.haml
= form_with(model: user_check, local: true) do |form|
  - if user_check.errors.any?
    #error_explanation
      %h2
        = pluralize(user_check.errors.count, "error")
        prohibited this user_check from being saved:
      %ul
        - user_check.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :checks, "."
    %br/
    .check
      %table
        %tr
          %th 質問番号
          %th 質問
          %th 知らない
          %th 聞いたことがある
          %th 大体わかる
          %th 人に教えられる
          %th 後でチェック
        
        = form.fields_for :checks do |addresses_form|
          %tr        
            = addresses_form.hidden_field :content_id,value:addresses_form.index+1
            %td
              =Content.find(addresses_form.index+1).id
            %td
              = addresses_form.label :level, " #{ Content.find(addresses_form.index+1).text}"
            %label
              %td
                = addresses_form.radio_button :level, 1
              %td
                = addresses_form.radio_button :level, 2
              %td
                = addresses_form.radio_button :level, 3
              %td
                = addresses_form.radio_button :level, 4
              %td
                = addresses_form.check_box 'flag', {}, "6", "5"
    .actions
      = form.submit
  -#     %table
  -#       %tr
  -#         %td
  -#         %td 登りたい
  -#         %td どちらでもない
  -#         %td 登りたくない
  -# %tr
  -#   %td 奥穂高岳
  -#   %td
  -#     %label
  -#       %input#d10-1{:name => "d10-1", :type => "radio"}/
  -#   %td
  -#     %label
  -#       %input#d10-2{:name => "d10-1", :type => "radio"}/
  -#   %td
  -#     %label
  -#       %input#d10-2{:name => "d10-1", :type => "radio"}/
  -# %tr
  -#   %td 槍ヶ岳
  -#   %td
  -#     %label
  -#       %input#d10-4{:name => "d10-2", :type => "radio"}/
  -#   %td
  -#     %label
  -#       %input#d10-5{:name => "d10-2", :type => "radio"}/
  -#   %td
  -#     %label
  -#       %input#d10-6{:name => "d10-2", :type => "radio"}/
  -# %tr
  -#   %td 燕岳
  -#   %td
  -#     %label
  -#       %input#d10-7{:name => "d10-2", :type => "radio"}/
  -#   %td
  -#     %label
  -#       %input#d10-8{:name => "d10-2", :type => "radio"}/
  -#   %td
  -#     %label
  -#       %input#d10-9{:name => "d10-2", :type => "radio"}/




                -# %input{:name => "user_check[checks_attributes][#{addresses_form.index}][flag]", :type => "hidden", :value => "0"}/
                -# %input#user_check_checks_attributes_0_flag{:name => "user_check[checks_attributes][#{addresses_form.index}][flag]", :type => "checkbox", :value => "1"  ,"#{=checked}"}/


-# = form_with(model: user_check, local: true) do |form|
-#   -# - if user_check.errors.any?
-#   -#   #error_explanation
-#   -#     %h2
-#   -#       = pluralize(user_check.errors.count, "error")
-#   -#       prohibited this user_check from being saved:
-#   -#     %ul
-#   -#       - user_check.errors.full_messages.each do |message|
-#   -#         %li= message


-#   .field
-#     = form.label :user_id
-#     = form.number_field :user_id
-#   .field
-#     = form.label :checks, "チェックス"
-#     %br/
-#     .check
-#       = form.fields_for :checks do |addresses_form|
-#         = addresses_form.hidden_field :content_id,value: 1
-#         = addresses_form.label :level, " レベル"
-#         %label
-#           = addresses_form.label "12", 12        
-#           = addresses_form.radio_button :level, 12
-#           = addresses_form.label "13", 13        
-#           = addresses_form.radio_button :level, 13
-#       %br/
-#       %label{:for => "user_check_checks_attributes_0_flag"} フラッグ
-#       %input{:name => "user_check[checks_attributes][0][flag]", :type => "hidden", :value => "5"}/
-#       %input#user_check_checks_attributes_0_flag{:name => "user_check[checks_attributes][0][flag]", :type => "checkbox", :value => "6"}/
-#       %br/
-#   .actions
-#     = form.submit

app/views/genres/haml.haml
= form_with(model: user_check, local: true) do |form|
  .field
    = form.label :user_id
    = form.number_field :user_id
  .field
    = form.label :checks, "チェックス"
    %br/
    = form.fields_for :checks do |addresses_form|
      = addresses_form.hidden_field :content_id,value: 1
      = addresses_form.label :level, " レベル"
      %label
        = addresses_form.label "12", 12        
        = addresses_form.radio_button :level, 12
        = addresses_form.label "13", 13        
        = addresses_form.radio_button :level, 13
      %br/
      %label{:for => "user_check_checks_attributes_0_flag"} フラッグ
      %input{:name => "user_check[checks_attributes][0][flag]", :type => "hidden", :value => "5"}/
      %input#user_check_checks_attributes_0_flag{:name => "user_check[checks_attributes][0][flag]", :type => "checkbox", :value => "6"}/
      %br/
  .actions
    = form.submit

↓使いたかった・・・・・・・！
      %br/
      = addresses_form.label :flag, "フラッグ"
      = addresses_form.check_box 'flag', {}, "6", "5"
      %br/
-# = addresses_form.check_box 'flag', {}, "6", "5" %>

-# = addresses_form.radio_button :level, 1 理解していない
-# = addresses_form.radio_button :level, 2 何となくわかる
-# = addresses_form.radio_button :level, 3 理解している
-# = addresses_form.radio_button :level, 4 わかりやすく説明できる
-# %label
-#   = addresses_form.radio_button :level, 1 理解していない
-# %label
-#   = addresses_form.radio_button :level, 2 何となくわかる
-# %label
-#   = addresses_form.radio_button :level, 3 理解している
-# %label
-#   = addresses_form.radio_button :level, 4 わかりやすく説明できる
      %br/
      %label{:for => "user_check_checks_attributes_0_flag"} フラッグ
      %input{:name => "user_check[checks_attributes][0][flag]", :type => "hidden", :value => "5"}/
      %input#user_check_checks_attributes_0_flag{:name => "user_check[checks_attributes][0][flag]", :type => "checkbox", :value => "6"}/
      %br/

app/views/genres/index.haml
- @genres.each do |genre|
  = link_to genre.name,genre_path(genre.id)
  = genre.contents.length

app/views/genres/new.haml
%h1 New User Check
= render 'form', user_check: @user_check
= link_to 'Back', user_checks_path

app/views/genres/show.haml
.content-box
  = form_with(model: @user_check, local: true) do |form|
    - if @user_check.errors.any?
      #error_explanation
        %h2
          = pluralize(@user_check.errors.count, "error")
          prohibited this @user_check from being saved:
        %ul
          - @user_check.errors.full_messages.each do |message|
            %li= message
    .field
      = form.hidden_field :genre_id,value:params[:id]
      = form.label :checks, "#{@genre.name}"
      %br/
      .check
        %table
          %tr
            %th 質問番号
            .question-content
              %th 質問
            %th 知らない
            %th 出来ない
            %th 出来る
            %th 人に教えられる
            %th 後でチェック
          
          = form.fields_for :checks do |addresses_form|
            %tr.hover        
              = addresses_form.hidden_field :content_id,value:addresses_form.index+@num
              %td
                =Content.find(addresses_form.index+1).id
              %td
                = link_to Content.find(addresses_form.index+@num).text,content_path(Content.find(addresses_form.index+@num).id)   
              %label
                %td
                  = addresses_form.radio_button :level, 1
                %td
                  = addresses_form.radio_button :level, 2
                %td
                  = addresses_form.radio_button :level, 3
                %td
                  = addresses_form.radio_button :level, 4
                %td
                  = addresses_form.check_box 'flag', {}, "6", "5"
      .actions
        = form.submit

app/views/likes/_like.haml
.like
  %span{:style => "color:#649CD1"}> like_count:
  %n
  %span{:style => "color:#C04761"}>       
    -if user_signed_in? && comment.like_users.include?(current_user)
      %i.fas.fa-heart
    - else            
      %i.far.fa-heart              
  =comment.likes.count
  ,
  %br/
  - if user_signed_in?    
    %span{:style => "color:#649CD1"}> like:
    %n
    -if comment.like_users.include?(current_user)
      =link_to "click",like_path(comment.likes.find_by!(user_id:current_user.id)), {class: 'dislikebutton' , method: :delete, remote: true}
      ,
    -else  
      = link_to 'click', likes_path(li: {user_id: current_user.id, comment_id: comment.id}), {class: 'likebutton' , method: :post, remote: true}
      ,

app/views/likes/like.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", story: @story  )) %>');