config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  get 'privacy_policy', to: 'contents#privacy_policy'
  get 'enter', to: 'users#enter'
  get 'about', to: 'users#about'
  get 'signup/oauth', to: 'signups#oauth'
  get 'signup/facebook', to: 'signups#oauth_facebook'
  root 'users#index'
  resources :users, only: :show
  resources :genres
  resources :user_checks
  resources :likes, only: %i[create destroy]
  resources :contents do
    resources :comments
  end
end

app/models/achievement.rb
class Achievement < ApplicationRecord
  belongs_to :user
  belongs_to :content
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check.rb
class Check < ApplicationRecord
  belongs_to :user_check
  belongs_to :content
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :content
  belongs_to :user
  validates :text, presence: true
  has_many :likes
  has_many :like_users, through: :likes, source: :user
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :genre, optional: true
  has_many :comments
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :contents
  has_many :user_checks
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
end

app/models/trophy.rb
class Trophy < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :user_checks
  has_many :checks, through: :user_checks
  has_many :likes
  has_many :comments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, omniauth_providers: %i[facebook google_oauth2]
  with_options presence: true do
    validates :email, :username, :start_date
  end
  validates :email, presence: true, uniqueness: true

  def self.from_omniauth(auth)
    @credential = SnsCredential.where(provider: auth.provider, uid: auth.uid, email: auth.info.email).first_or_create
    @user = User.where(email: auth.info.email).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.password_confirmation = Devise.friendly_token[0, 20]
    end
    @user
  end

  def trophies
    @trophys = []
    comments_length = comments.length
    likes_length = likes.length
    comment_trophies(comments_length)
    like_trophies(likes_length)
    @trophys
  end

  def comment_trophies(comments_length)
    @trophys << Trophy.find(8) if comments_length >= 1
    @trophys << Trophy.find(9) if comments_length >= 10
    @trophys << Trophy.find(10) if comments_length >= 50
    @trophys << Trophy.find(11) if comments_length >= 100
  end

  def like_trophies(likes_length)
    @trophys << Trophy.find(12) if likes_length >= 10
    @trophys << Trophy.find(13) if likes_length >= 50
  end

  def remember_me
    true
  end
end

app/models/user_check.rb
class UserCheck < ApplicationRecord
  has_many :checks
  accepts_nested_attributes_for :checks
  belongs_to :user
  belongs_to :genre
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def index
    @contents = Content.all
  end

  def show
    @content = Content.find(params[:id])
    @comments = @content.comments
    @comment = Comment.new
  end

  def create; end

  def privacy_policy; end

  def edit; end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
    @comments = Comment.all
  end

  def show
    @genre = Genre.find(params[:id])
    @num = @genre.contents.first.id
    return true if @user_check = UserCheck.find_by(user_id: current_user.id, genre_id: params[:id])

    @user_check = UserCheck.new
    Genre.find(params[:id]).contents.length.times { @user_check.checks.build }
  end

  def new
    @user_check = UserCheck.new
    @user_checks = Content.last.id.times do
      @user_check.checks.build
    end
  end

  def edit
    @user_check = UserCheck.find_by(user_id: current_user.id)
    @checks = @user_check.checks.firstend
  end

  def create
    @user_check = current_user.user_checks.create(user_check_params)
    redirect_to root_path
  end

  def update
    @user_check = current_user.user_checks.update(user_check_params)
    redirect_to root_path
  end

  def user_check_params
    params.require(:user_check).permit(
      :genre_id,
      :user_id,
      checks_attributes: %i[id level flag content_id]
    )
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @comment = Comment.find(params[:li][:comment_id])
    @comment.likes.create(user_id: current_user.id)
    redirect_to content_url(id: @comment.content_id)
  end

  def destroy
    @like = Like.find(params[:id]).destroy
    redirect_to content_url(id: @like.comment.content_id)
  end

  private

  def likes_params
    params.require(:likes).permit(:user_id, :comment_id)
  end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  def sms_confirmation_send
    @profile = Profile.new
    flash.delete(:notice)
  end

  def sms_confirmation_certify
    @profile = current_user.profile.assign_attributes(profile_params)
    if current_user.profile.valid?(:sms_confirmation_send)
      current_user.profile.update(profile_params)
    else
      @profile = Profile.new
      @errors = '未記入箇所があります'
      render 'sms_confirmation_send'
    end
  end

  def oauth
    @user = User.new
    @user.email = session['devise.google_data']['info']['unverified_email'] if session['devise.google_data']
    @user.email = session['devise.facebook_data']['info']['email'] if session['devise.facebook_data']
  end

  def oauth_facebook
    @user = User.new
    @user.email = session["devise.facebook_data"]['info']['email']
  end

  def index; end

  def new; end

  def show; end

  def succesful; end

  private

  def profile_params
    params.require(:profile).permit(:phone_number, :family_name, :last_name, :kana_family_name, :kana_last_name, :postalcode, :address_prefecture, :address_city, :address_street_number, :address_building_name)
  end

  def use_check_address_nil?
    false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def enter
    render layout: nil
  end

  def about; end

  def index; end

  def show
    @user = User.find(params[:id])
    @trophys = @user.trophies
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find(session[:user_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/user_checks_helper.rb
module UserChecksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contents/index.haml
.content-box
  - @contents.each do|content|
    =link_to content.text,content_path(content.id)
    %br

app/views/contents/privacy_policy.haml
.privacy
  %h3 プライバシーポリシー
  %p 本プライバシーポリシーは、Web programing skill check test （URL:https://web-skill-check-sheet.herokuapp.com/）（以下、「当サイト」と言います。）における、利用者（以下、「ユーザー」と言います。）に関する個人情報の保護及び適切な取り扱いについての方針を示したものです。
  %p 
  %h5 1.基本方針
  %p 当サイトは、ユーザーの個人情報を保護することが当サイトの事業活動の基本であるとともに、社会的責務と認識し、個人情報の取得、利用、管理を適正に行います。当サイトで収集した情報は、利用目的の範囲内で適切に取り扱います。
  %h5 2.適用範囲
  %p 本プライバシーポリシーは、当サイトにおいてのみ適用されます。 なお、当サイトにおいて、コメントの投稿、お問い合わせ、各サービスのお申し込みをした時点で、本プライバシーポリシーに同意されたものとみなします。
  %h5 3.個人情報の取得
  %p 当サイトで取得するユーザーの個人情報は次のとおりです。
  %p 
  %h6 3-1.ユーザー新規登録
  %p ユーザー新規登録ページから新規登録をした際、次の個人情報を取得します。
  %p ・ 名前（ハンドルネーム）
  %p ・ メールアドレス
  %p ・ プログラミング学習開始時期
  %h6 3-2.ユーザーチェックシート回答
  %p ユーザーが当サイトの各サービスページなどに設置されたお申し込みフォームから申し込みをした際、次の個人情報を取得します。
  %p ・ 回答内容
  %h6 3-3.コメント欄
  %p ユーザーが各記事ページの末尾などに設置されたコメント欄に投稿した際、次の個人情報を取得します。
  %p ・ 名前（ハンドルネーム）
  %p ・ メールアドレス
  %p ・ コメント内容
  %p 
  %h5 4.個人情報の利用
  %p 当サイトで取得した個人情報の利用目的は次のとおりです。
  %p ・ コメント欄の荒し対策やスパム検出に役立てるため。
  %p ・ コメントやお問い合わせに適時且つ正確に応答するため。
  %p ・ 当サイト内でコメントやお問い合わせ内容を引用して紹介させていただく場合もあります。
  %p ・ 各サービスに適時且つ正確に応対するため。
  %h5 5.個人情報の保存期間
  %p 当サイトに投稿されたコメント、各サービスに関する情報は無期限で保存されます。但し、当サイトの判断により、関する情報が不要となった場合には、速やかに削除されます。
  %h5 6.個人情報の管理
  %p 当サイトは、個人情報に関する法令、規範を遵守し、個人情報の管理責任者を置き、個人情報の保護に努めています。
  %p ・ 当サイトは、ユーザーの個人情報を安全且つ正確に管理し、個人情報への不正アクセス、紛失、破壊、改ざん及び漏洩などを防止するための措置を講じています。
  %p ・ 当サイトは、次に掲げる場合を除き、予めユーザーの同意を得ないで個人情報を第三者に提供いたしません。また、当サイトが個人情報の処理を外部へ委託する場合には、当サイトと同様に適切な管理を行うよう、契約によって義務付けています。
  %p ・ 個人情報保護に関する法律第23条第2項ないし同第4項の方法による場合
  %p ・ 法令などの規定に従い提供または開示する場合
  %p ・ 各種案内等を送付するにあたり、郵便局や宅配便会社に宛先を指定する場合
  %p ・ 当サイトは、ユーザーが、ユーザー本人の個人情報の開示、訂正、追加、削除、利用停止などを希望される場合、または、ユーザーに提供（送付）する各種案内の停止を希望される場合には、連絡を受け次第速やかに対応しています。
  %p ・ 当サイトは、個人情報に関して適用される法令、規範などを遵守するとともに、上記各項における個人情報の取扱いを監査し継続的に見直し、改善に努めています。
  %h5 7.プライバシーポリシーの変更について
  %p 当サイトは、個人情報に関して適用される日本の法令を遵守するとともに、本プライバシーポリシーの内容を適宜見直しその改善に努めます。改訂された最新の内容は常に本ページにて開示されます。
  %h5 8.お問い合わせ窓口
  %p Web programing skill check test  お問い合わせ：https://twitter.com/127haruki までDMにてお問い合わせください
  %p 2019年7月4日 策定

app/views/contents/show.haml
.content-box
  = link_to root_path  do
    Top
  >
  - if user_signed_in?  
    = link_to @content.genre.name,genre_path(@content.genre.id)   
  - else
    = @content.genre.name
.comments
  - if @comment.errors.any?
    #error_explanation
      %h2
        = pluralize(@comment.errors.count, "error")
        prohibited this comment from being saved:
        - @comment.errors.full_messages.each do |message|
          %li = message
  .title
    %span{style: "color:#649CD1"}> title:
    = @content.text
  %br
  comments = [
  %br/
  %br
    - @comments.each.with_index do |comment,i|
      .comment
        {
        %br
        %span{style:  "color:#649CD1"}> comment_id:
        %n
        =i
        ,
        %br
        %span{:style => "color:#649CD1"}> name:
        &nbsp;
        %span{:style => "color:#C69373"}> 
          '
          =comment.user.username  
          さん',
        %br/

        %span{:style => "color:#649CD1"}> text:
        %n
        %span{:style => "color:#C69373"}> 
          <<-TEXT,
          =raw Rinku.auto_link(h(simple_format(comment.text, {}, wrapper_tag: "div") ))
          TEXT
        %br/

        %span{:style => "color:#649CD1"}> created_at:  
        %n
        %span{:style => "color:#BACDAB"}> 
          =comment.created_at.strftime('%Y/%m/%d %R')
        ,
        %br/
        = render 'likes/like',comment: comment 

        -if user_signed_in? && comment.user == current_user

          %span{:style => "color:#649CD1"}> edit:
          %n
            =link_to "click",edit_content_comment_path( @content,comment.id),class: 'edit_commment_button'
            ,
          %br
          %span{:style => "color:#649CD1"}> delete:
          %n
            =link_to "click",content_comment_path( @content,comment.id), {class: 'destroy_commment_button' , method: :delete}
          %br
        }
        -unless i == @comments.length - 1
          ,
          %br/
          %br/

    ]
  -if user_signed_in?  
    .form
      = form_for [@content, @comment] do |f|
        .input-box
          .input-box__text
            = f.hidden_field :content_id,value:params[:id]
            = f.text_area :text, placeholder: 'type a message'
          .input-box__submit-btn
            = f.submit 
  %br/
  %br/