config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  get 'privacy_policy', to: 'contents#privacy_policy'
  get 'enter', to: 'users#enter'
  get 'about', to: 'users#about'
  get 'signup/oauth', to: 'signups#oauth'
  get 'signup/facebook', to: 'signups#oauth_facebook'
  root 'users#index'
  resources :users, only: :show
  resources :genres
  resources :user_checks
  resources :likes, only: %i[create destroy]
  resources :contents do
    resources :comments
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :user_checks
  has_many :checks, through: :user_checks
  has_many :likes
  has_many :comments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, omniauth_providers: %i[facebook google_oauth2]
  with_options presence: true do
    validates :email, :username, :start_date
  end
  validates :email, presence: true, uniqueness: true

  def self.from_omniauth(auth)
    @credential = SnsCredential.where(provider: auth.provider, uid: auth.uid, email: auth.info.email).first_or_create
    @user = User.where(email: auth.info.email).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.password_confirmation = Devise.friendly_token[0, 20]
    end
    @user
  end

  def trophies
    @trophys = []
    comments_length = comments.length
    likes_length = likes.length
    comment_trophies(comments_length)
    like_trophies(likes_length)
    @trophys
  end

  def comment_trophies(comments_length)
    @trophys << Trophy.find(8) if comments_length >= 1
    @trophys << Trophy.find(9) if comments_length >= 10
    @trophys << Trophy.find(10) if comments_length >= 50
    @trophys << Trophy.find(11) if comments_length >= 100
  end

  def like_trophies(likes_length)
    @trophys << Trophy.find(12) if likes_length >= 10
    @trophys << Trophy.find(13) if likes_length >= 50
  end

  def remember_me
    true
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # callback for facebook
  def facebook
    callback_for(:facebook)
  end

  # callback for google
  def google_oauth2
    callback_for(:google)
  end

  # common callback method
  def callback_for(provider)
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: provider.to_s.capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth'].except('extra')
      # redirect_to "/signup/#{provider}"
      redirect_to '/signup/oauth'
    end
  end

  def failure
    redirect_to top_index_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
    @user.email = session['devise.google_data']['info']['unverified_email'] if session['devise.google_data']
    @user.email = session['devise.facebook_data']['info']['email'] if session['devise.facebook_data']
    @user.email = 'ssssss'
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def enter
    render layout: nil
  end

  def about; end

  def index; end

  def show
    @user = User.find(params[:id])
    @trophys = @user.trophies
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/about.haml
.about-wrapper
  .about-wrapper__contents
    %h4 このサイトについて
    当サイトは株式会社X-HACK代表の松田信介さんが考案された 
    %br/
    webエンジニア初学者に知ってほしい 関連知識のチェックシートを webサイトにしたものです。 
    %br/
    これを使って自身の知識を確認していくと 一通りの知識が入るようになっております。 
    %br/
    現在勉強されている方は 自分の不足しているスキルをチェックする用途で使用することができます。 
    %br/
    勉強を始めたばかりの方には これから学ばなければならないことの全体像の把握に使っていただければ幸いです。 
  .about-wrapper__contents
    %br/
    %h4  使い方
    %br/
    %h5 トップページ
    左下の項目一覧より、確認したい項目を選択し、回答してください。
    %br/
    その際、「後でチェック」を選択すると今後取り組みたい課題として左上に表示されます。
    %br/
    「出来る」以上を選択した質問がユーザーの習得済みスキルとしてみなされます。
    %br/
    %br/
    %h5 質問ページ
    個別の質問をクリックしていただくと質問毎の専用ページに遷移します。
    %br/ 
    コメントもできるので質問に関連するわからないことや、参考になったサイトなどをコメントいただけると幸いです。
    %br/
    コメントにはlikeボタンが実装されております、参考になったコメントには押していきましょう。
    %br/
    %br/
  
    %h5 マイページ
    全ユーザーの中での習得率の順位、獲得したメダルやトロフィーを確認できます。
    %br/
    メダル……回答に応じて獲得できます
    %br
    トロフィー……獲得したメダル数、コメント数、良いね の数に応じて獲得できます。

  .about-wrapper__contents
    %br/
    %h4 関連リンク
    = link_to  'プライバシーポリシー',privacy_policy_path
    %br/
    当サイトのプライバシーポリシーです。
    %br/
    %br/
    = link_to 'Webプログラミングスキルチェックシート(初級)','https://note.mu/xhack/n/n44867c8d247b'
    %br/
    元ネタの記事です。許可をいただいで転載しております。
    %br/
    %br
    = link_to 'X-HACK東京 - connpass','https://x-hack.connpass.com/'
    %br/
    X-HACKさんの勉強会の応募サイトです。勉強会のタイトルを眺めるだけでもどんな知識が大切なのかわかります。
    %br/
    良心的なことに現在はこれまでの勉強会の資料を無料で閲覧することもできます。参考になったら勉強会に参加しましょう。
    %br/
    %br

    = link_to 'https://twitter.com/XHACK20','https://twitter.com/XHACK20'
    %br/
    松田信介さんのTwitterアカウントです。勉強に関することやwebプログラミング全般のことなどについて呟かれていて勉強になります。
    %br/
    %br/

    = link_to 'https://twitter.com/127haruki','https://twitter.com/127haruki'
    %br/
    作者のTwitterアカウントです。アプリの使っての感想やご意見などございましたら 以下のアカウントまでご連絡ください。

    %br/

app/views/users/enter.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Webプログラミングスキルチェックシート
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    %link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css", :integrity => "sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T", :rel => "stylesheet"}/
    %link{:href => "https://use.fontawesome.com/releases/v5.6.3/css/all.css", :rel => "stylesheet"}/
  %body
.enter-wrapper
  .flame.first
    .title
      WEB PROGRAMMING        
      %br/
      SKILL CHECK SHEET
      .subtitle
        初心者webエンジニアのためのスキルチェックシート
  .flame.second
    .content
      .title
        初めてwebプログラミングを勉強するのは難しい
    %br/
    .paragraph
      新しい技術であるため教材が洗練されていない
      %br/
      ーーーhttp、www、セキュリティ、DBーーー
      %br/
      周辺知識が多く何をやったらいいかわからない
      %br/
    .paragraph
      スクールに通った方がいいの？独学がいいの？
      %br/
    .inpact
      web programming skill check sheetが解決します
  .flame.third
    .title
      web programming skill check sheet
    %br 
    そんな初学者の悩みを解決するため
    %br 
    .top-link
      = link_to 'https://twitter.com/XHACK20', method: :get  do
        株式会社X-HACK代表の松田さん
      は
    webエンジニア初学者に知ってほしい
    %br 
    関連知識のチェックシートを考案しました。
    %br 
    %br/
    当サイトはそのチェックシートを
    %br/
    webサイトにしたものです。
    %br 
    %br/
    これを使って自身の知識を確認していくと
    %br/
    一通りの知識が入るようになっております。
  .flame.fourth
    .content
      %br/
      現在勉強されている方は
      %br/
      自分の不足しているスキルをチェックする用途で使用することができます。
      %br/
      %br/
      勉強を始めたばかりの方には
      %br/
      これから学ばなければならないことの全体像の把握に使っていただければ幸いです。
      %br/
      %br/
      .last-notice
        暗記する必要のある項目は少ない
        %br/
        調べながらでも構わないので
        %br/
        ドンドンチェックして行きましょう！
        = link_to new_user_session_path, method: :get  do
          .signup
            新規登録
        = link_to new_user_registration_path, method: :get  do
          .login
            ログイン
  %script{:crossorigin => "anonymous", :integrity => "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo", :src => "https://code.jquery.com/jquery-3.3.1.slim.min.js"}
  %script{:crossorigin => "anonymous", :integrity => "sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1", :src => "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"}
  %script{:crossorigin => "anonymous", :integrity => "sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM", :src => "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"}
    .footer

app/views/users/index.haml
%aaaa

app/views/users/show.haml
.mypage-wrapper
  .jumbotron.jumbotron-fluid.user-name
    .container
      %h1.display-7 
        =@user.username
        さんのマイページ
      %p.lead 取得したトロフィーの数などが確認できます
  .container
    .row
      .col-sm-12.col-lg-6.ranking
        %h1.display-8 ランキング
        %h1.display-4 
          = User.order(rank: :DESC).index(@user) + 1
          位
          /
          = User.all.length
          人中
        %br/
      .col-sm-12.col-lg-6.start-date
        %h1.display-8 勉強開始時期
        %h1.display-4 
        .study_start
          =@user.start_date.year
          年
          =@user.start_date.month
          月
        %br/
  .jumbotron.jumbotron-fluid.title-medal
    .container
      %h1.display-7 メダル獲得状況
      %p.lead 出来るを選択したチェック項目を習得したものと見なし、数に応じてメダルを獲得することができます。
  .container
    .row
      - user_checked_cnt_all=[] 
      - @genres.each do |genre|
        .col-sm-12.col-lg-6.checkmedal
          
          = link_to genre.id.to_s+"."+genre.name,genre_path(genre.id) 
          
          = genre.contents.length
          問中


          - if User.find(params[:id]).user_checks.find_by(genre_id:genre.id).present?
          
            - user_checked_cnt=User.find(params[:id]).user_checks.find_by(genre_id:genre.id).checks.where(["level > ? ", 2]).length 
            - user_checked_cnt_all << user_checked_cnt
            = user_checked_cnt
            問出来る
            - case user_checked_cnt/genre.contents.length.to_f
              - when 1
                = image_tag Trophy.find(3).image_url, :alt => '登録ボタン',:size =>'100x100'
              - when (0.8...1)
                = image_tag Trophy.find(2).image_url, :alt => '登録ボタン',:size =>'100x100'
              - when (0.5...0.8)
                = image_tag Trophy.find(1).image_url, :alt => '登録ボタン',:size =>'100x100'
          - else
            未実施です
  .jumbotron.jumbotron-fluid.title-skill
    .container
      %h1.display-4 
        取得済スキル：
        = user_checked_cnt_all.compact.sum.to_s+"個/"
        = Content.all.length.to_s+"個" 
      %br/
      .progress{:style => "height: 50px;"}
        .progress-bar{:role => "progressbar", :style => "width: #{(user_checked_cnt_all.compact.sum/Content.all.length.to_f*100).floor}%;"}
  .jumbotron.jumbotron-fluid.title-trophy
    .container
      %h1.display-7 トロフィー獲得状況
      %p.lead コメント数、メダル数やいいねの数に応じてトロフィーが表示されます。
  .container
    .row
      - @trophys.each do|trophy| 
        .col-xs-12.col-sm-12.col-md-6.col-lg-3.trophy
          #trophy-box
            %br/
            .trophyname
              = trophy.name
            %br/
            .trophyimage
              = image_tag trophy.image_url, :alt => '登録ボタン',:size =>'100x100'
            %br/
            .trophytext
              = trophy.text
      .col-xs-12.col-sm-12.col-md-6.col-lg-3.trophy
      .col-xs-12.col-sm-12.col-md-6.col-lg-3.trophy
      .col-xs-12.col-sm-12.col-md-6.col-lg-3.trophy
      .col-xs-12.col-sm-12.col-md-6.col-lg-3.trophy
  .jumbotron.jumbotron-fluid.title-got-trophy
    .container
      %h1.display-4 
        取得済トロフィー：
        = @trophys.length.to_s+"個/"
        = "10個" 
      %br/
      .progress{:style => "height: 50px;"}
        .progress-bar.trophy-bar{:role => "progressbar", :style => "width: #{(@trophys.length/10.to_f*100).floor}%;"}

app/views/users/show.html.haml
.mypage-wrapper
  .jumbotron.jumbotron-fluid.user-name
    .container
      %h1.display-7 
        =current_user.username
        さんのマイページ
      %p.lead 取得したトロフィーの数などが確認できます
  .container
    .row
      .col-6.ranking
        %h1.display-8 ランキング
        %h1.display-4 
          = User.order(rank: :DESC).index(current_user) + 1
          位
          /
          = User.all.length
          人中
        %br/
        
      
      .col-6.start-date
        %h1.display-8 勉強開始時期
        %h1.display-4 
        .study_start
          =@user.start_date.year
          年
          =@user.start_date.month
          月
        %br/
        

  .jumbotron.jumbotron-fluid.title-medal
    .container
      %h1.display-7 メダル獲得状況
      %p.lead 出来るを選択したチェック項目を習得したものと見なし、数に応じてメダルを獲得することができます。
  .container
    .row
      
      -user_checked_cnt_all=[] 
      - @genres.each do |genre|
        .col-6.checkmedal
          
          = link_to genre.id.to_s+"."+genre.name,genre_path(genre.id) 
          
          = genre.contents.length
          問中


          -if User.find(params[:id]).user_checks.find_by(genre_id:genre.id).present?
          
            -user_checked_cnt=User.find(params[:id]).user_checks.find_by(genre_id:genre.id).checks.where(["level > ? ", 2]).length 
            - user_checked_cnt_all << user_checked_cnt
            =user_checked_cnt
            問出来る
            -case user_checked_cnt/genre.contents.length.to_f
              -when 1
                = image_tag Trophy.find(3).image_url, :alt => '登録ボタン',:size =>'100x100'
              - when (0.8...1)
                = image_tag Trophy.find(2).image_url, :alt => '登録ボタン',:size =>'100x100'
              - when (0.5...0.8)
                = image_tag Trophy.find(1).image_url, :alt => '登録ボタン',:size =>'100x100'
          -else
            未実施です

  .jumbotron.jumbotron-fluid.title-skill
    .container
      %h1.display-4 
        取得済スキル：
        =user_checked_cnt_all.compact.sum.to_s+"個/"
        =Content.all.length.to_s+"個" 
      %br/
      .progress{:style => "height: 50px;"}
        .progress-bar{:role => "progressbar", :style => "width: #{(user_checked_cnt_all.compact.sum/Content.all.length.to_f*100).floor}%;"}




  .jumbotron.jumbotron-fluid.title-trophy
    .container
      %h1.display-7 トロフィー獲得状況
      %p.lead コメント数、メダル数やいいねの数に応じてトロフィーが表示されます。

  .container
    .row
      -@trophys.each do|trophy| 
        .col-xs-12.col-sm-6.col-md-3.trophy
          %okodkoddod
          %br/
          .trophyname
            =trophy.name
          %br/
          .trophyimage
            = image_tag trophy.image_url, :alt => '登録ボタン',:size =>'100x100'
          %br/
          .trophytext
            =trophy.text

      .col-xs-12.col-sm-6.col-md-3.trophy
      .col-xs-12.col-sm-6.col-md-3.trophy
  .jumbotron.jumbotron-fluid.title-got-trophy
    .container
      %h1.display-4 
        取得済トロフィー：
        =@trophys.length.to_s+"個/"
        ="10個" 
      %br/
      .progress{:style => "height: 50px;"}
        .progress-bar.trophy-bar{:role => "progressbar", :style => "width: #{(@trophys.length/10.to_f*100).floor}%;"}