config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  get 'privacy_policy', to: 'contents#privacy_policy'
  get 'enter', to: 'users#enter'
  get 'about', to: 'users#about'
  get 'signup/oauth', to: 'signups#oauth'
  get 'signup/facebook', to: 'signups#oauth_facebook'
  root 'users#index'
  resources :users, only: :show
  resources :genres
  resources :user_checks
  resources :likes, only: %i[create destroy]
  resources :contents do
    resources :comments
  end
end

app/models/achievement.rb
class Achievement < ApplicationRecord
  belongs_to :user
  belongs_to :content
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check.rb
class Check < ApplicationRecord
  belongs_to :user_check
  belongs_to :content
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :content
  belongs_to :user
  validates :text, presence: true
  has_many :likes
  has_many :like_users, through: :likes, source: :user
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :genre, optional: true
  has_many :comments
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :contents
  has_many :user_checks
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
end

app/models/trophy.rb
class Trophy < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :user_checks
  has_many :checks, through: :user_checks
  has_many :likes
  has_many :comments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, omniauth_providers: %i[facebook google_oauth2]
  with_options presence: true do
    validates :email, :username, :start_date
  end
  validates :email, presence: true, uniqueness: true

  def self.from_omniauth(auth)
    @credential = SnsCredential.where(provider: auth.provider, uid: auth.uid, email: auth.info.email).first_or_create
    @user = User.where(email: auth.info.email).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.password_confirmation = Devise.friendly_token[0, 20]
    end
    @user
  end

  def trophies
    @trophys = []
    comments_length = comments.length
    likes_length = likes.length
    comment_trophies(comments_length)
    like_trophies(likes_length)
    @trophys
  end

  def comment_trophies(comments_length)
    @trophys << Trophy.find(8) if comments_length >= 1
    @trophys << Trophy.find(9) if comments_length >= 10
    @trophys << Trophy.find(10) if comments_length >= 50
    @trophys << Trophy.find(11) if comments_length >= 100
  end

  def like_trophies(likes_length)
    @trophys << Trophy.find(12) if likes_length >= 10
    @trophys << Trophy.find(13) if likes_length >= 50
  end

  def remember_me
    true
  end
end

app/models/user_check.rb
class UserCheck < ApplicationRecord
  has_many :checks
  accepts_nested_attributes_for :checks
  belongs_to :user
  belongs_to :genre
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @comment = Comment.find(params[:li][:comment_id])
    @comment.likes.create(user_id: current_user.id)
    redirect_to content_url(id: @comment.content_id)
  end

  def destroy
    @like = Like.find(params[:id]).destroy
    redirect_to content_url(id: @like.comment.content_id)
  end

  private

  def likes_params
    params.require(:likes).permit(:user_id, :comment_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def enter
    render layout: nil
  end

  def about; end

  def index; end

  def show
    @user = User.find(params[:id])
    @trophys = @user.trophies
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find(session[:user_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/user_checks_helper.rb
module UserChecksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_notifications.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"}
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Webプログラミングスキルチェックシート
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    %link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css", :integrity => "sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T", :rel => "stylesheet"}/
    %link{:href => "https://use.fontawesome.com/releases/v5.6.3/css/all.css", :rel => "stylesheet"}/

  %body
  .flash-messages.flash-messages__show
    = render 'layouts/notifications'
  .wrapper
    .side-bar
      .top-link
        -if user_signed_in?
          = link_to user_path(current_user.id)  do
            .side-bar__header
              Web programing skill check test
        -else
          = link_to root_path  do
            .side-bar__header
              Web programing skill check test
      .side-bar__contents
        .label
          取り組みたい課題
        .todo
          -if @todo_contents.present?
            -@todo_contents.each do |check| 
              #todo_link
                -link_title=check.content.text+"("+ check.content.genre.name + ")"
                =link_to link_title,content_path(check.content.id)  
                %br/
        .contents    
          .label
            項目一覧（習得率）
          -if user_signed_in?  
            .list      
              -user_checked_cnt_all=[] 
              - @genres.each.with_index do |genre,i|
                #content
                  = link_to genre_path(genre.id) do
                    =i+1  
                    ．
                    =genre.name   
                  = genre.contents.length
                  問中
                  -if user_signed_in?
                    -if genre.user_checks.find_by(user_id: current_user.id).present?&&genre.user_checks.find_by(user_id: current_user.id).score.present?

                      -user_checked_cnt=genre.user_checks.find_by(user_id: current_user.id).score 
                      =user_checked_cnt
                      問は理解しています
                    -else
                      未実施です
                  - user_checked_cnt_all << user_checked_cnt
                  %br        
              %n
              %n
              %n            
              合計：１８５問中
              =user_checked_cnt_all.compact!.sum unless Rails.env == 'test'
              問習得済み
              %br 
              %br 
    .main
      .header
        %ul.lists
          = link_to contents_path  do
            %li.list
              %span{:style => "color: Tomato;"}
                %i.fas.fa-home
              問題一覧
          = link_to about_path do
            %li.list
              %span{:style => "color: Dodgerblue;"}
                %i.fas.fa-question-circle
              about
          -if user_signed_in?
            = link_to user_path(current_user.id)  do
              %li.list 
                %span{:style => "color: Mediumslateblue;"}
                  %i.fas.fa-address-card 
                マイページ
            = link_to destroy_user_session_path , method: :delete do
              %li.list
                %span{:style => "color: Tomato;"}
                  %i.fas.fa-sign-out-alt 
                ログアウト                
          -else
            = link_to new_user_session_path, method: :get  do
              %li.list
                %span{:style => "color: Mediumslateblue;"}
                  %i.fas.fa-sign-out-alt 
                ログイン
            = link_to new_user_registration_path, method: :get  do
              %li.list 
                %span{:style => "color: Mediumslateblue;"}
                  %i.fas.fa-sign-out-alt 
                新規登録       
      .main-container
        = yield
      %script{:crossorigin => "anonymous", :integrity => "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo", :src => "https://code.jquery.com/jquery-3.3.1.slim.min.js"}
      %script{:crossorigin => "anonymous", :integrity => "sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1", :src => "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"}
      %script{:crossorigin => "anonymous", :integrity => "sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM", :src => "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"}
  .footer
    %script{:crossorigin => "anonymous", :integrity => "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo", :src => "https://code.jquery.com/jquery-3.3.1.slim.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1", :src => "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM", :src => "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"}